# VERİ ÖN HAZIRLIK VE TEMEL BİLGİLER

In [1]:
import pandas as pd 
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
df_ = pd.read_excel('gezinomi_data.xlsx')
df = df_.copy()
pd.set_option('display.float_format', lambda x: '%.2f' % x)
print(df.head())
print(df.shape)
print(df.info())

   SaleId   SaleDate CheckInDate  Price     ConceptName SaleCityName  \
0  415122 2022-12-03  2022-12-03  79.30    Herşey Dahil      Antalya
1  415103 2022-12-03  2022-12-03  45.97  Yarım Pansiyon      Antalya
2  404034 2022-09-12  2022-09-13  77.84    Herşey Dahil      Antalya
3  415094 2022-12-03  2022-12-10 222.71  Yarım Pansiyon        İzmir
4  414951 2022-12-01  2022-12-03 140.48  Yarım Pansiyon        İzmir

     CInDay  SaleCheckInDayDiff Seasons
0  Saturday                   0     Low
1  Saturday                   0     Low
2   Tuesday                   1    High
3  Saturday                   7     Low
4  Saturday                   2     Low
(59164, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59164 entries, 0 to 59163
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SaleId              59164 non-null  int64
 1   SaleDate            59164 non-null  datetime64[ns]
 2   CheckInDate         59164 non-null  datetime64[ns]
 3   Price               59151 non-null  float64
 4   ConceptName         59164 non-null  object
 5   SaleCityName        59164 non-null  object
 6   CInDay              59164 non-null  object
 7   SaleCheckInDayDiff  59164 non-null  int64
 8   Seasons             59164 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(4)
memory usage: 4.1+ MB
None

#### Soru 2: Kaç unique şehir vardır? Frekansları nedir?

In [2]:
df["SaleCityName"].nunique()

6

In [3]:
df["SaleCityName"].value_counts()

Antalya    31649
Muğla      10662
Aydın      10646
Diğer       3245
İzmir       2507
Girne        455
Name: SaleCityName, dtype: int64

####  Soru 3: Kaç unique Concept vardır?
#### Soru 4: Hangi Concept’den kaçar tane satış gerçekleşmiş?

In [4]:
df["ConceptName"].nunique()

3

In [5]:
df["ConceptName"].value_counts()

Herşey Dahil      53186
Yarım Pansiyon     3559
Oda + Kahvaltı     2419
Name: ConceptName, dtype: int64

#### Soru 5: Şehirlere göre satışlardan toplam ne kadar kazanılmış?

In [6]:
df.groupby("SaleCityName").agg({"Price": "sum"})

                  Price
SaleCityName
Antalya      2041911.10
Aydın         573296.01
Diğer         154572.29
Girne          27065.03
Muğla         665842.21
İzmir         165934.83

#### Soru 6: Concept türlerine göre göre ne kadar kazanılmış?

In [7]:
#groupby fonksiyonunda parametreyi ister "by=" ile ister yazmadan kullanabiliriz.
df.groupby(by="ConceptName").agg({"Price": "sum"})

                    Price
ConceptName
Herşey Dahil   3332910.77
Oda + Kahvaltı  121308.35
Yarım Pansiyon  174402.35

#### Soru 7: Şehirlere göre PRICE ortalamaları nedir?

In [8]:
df.groupby(by="SaleCityName").agg({"Price": "mean"})

              Price
SaleCityName
Antalya       64.52
Aydın         53.86
Diğer         47.71
Girne         59.48
Muğla         62.46
İzmir         66.27

#### Soru8:Conceptlere görePRICEortalamalarınedir?

In [9]:
df.groupby(by="ConceptName").agg({"Price": "mean"})

                Price
ConceptName
Herşey Dahil    62.67
Oda + Kahvaltı  50.25
Yarım Pansiyon  49.03

#### Soru 9: Şehir-Concept kırılımında PRICE ortalamaları nedir?

In [10]:
df.groupby(["SaleCityName", "ConceptName"]).agg({"Price": "mean"})

                             Price
SaleCityName ConceptName
Antalya      Herşey Dahil    64.52
             Oda + Kahvaltı  63.50
             Yarım Pansiyon  67.19
Aydın        Herşey Dahil    54.00
             Oda + Kahvaltı  34.46
             Yarım Pansiyon  30.02
Diğer        Herşey Dahil    84.77
             Oda + Kahvaltı  37.60
             Yarım Pansiyon  42.11
Girne        Herşey Dahil    97.68
             Oda + Kahvaltı  39.78
             Yarım Pansiyon  53.25
Muğla        Herşey Dahil    63.02
             Oda + Kahvaltı  59.04
             Yarım Pansiyon  45.12
İzmir        Herşey Dahil    74.70
             Oda + Kahvaltı  41.32
             Yarım Pansiyon  59.61

### Görev 2: SaleCheckInDayDiff değişkenini kategorik bir değişkene çeviriniz.

In [11]:
bins = [-1 , 7 , 30 , 60 , df["SaleCheckInDayDiff"].max()]
labels = ["Last Minuters", "Potential Planners", "Planners", "Early Bookers"]

df["EB_Score"] = pd.cut(df["SaleCheckInDayDiff"], bins, labels=labels)
df.head(50).to_excel("eb_score.xlsx" ,index=False)

### Görev 3: COUNTRY, SOURCE, SEX, AGE kırılımında ortalama kazançlar nedir?

In [12]:
df.groupby(["SaleCityName", "ConceptName", "EB_Score"]).agg({"Price": ["mean","count"]})

                                                Price
                                                 mean  count
SaleCityName ConceptName    EB_Score
Antalya      Herşey Dahil   Last Minuters       62.75  14148
                            Potential Planners  64.90   8874
                            Planners            67.51   3201
                            Early Bookers       67.14   4570
             Oda + Kahvaltı Last Minuters       65.35    503
                            Potential Planners  57.74     75
                            Planners            45.64      9
                            Early Bookers       32.91     11
             Yarım Pansiyon Last Minuters       70.43    204
                            Potential Planners  55.64     39
                            Planners            58.03      9
                            Early Bookers       35.03      4
Aydın        Herşey Dahil   Last Minuters       51.71   3965
                            Potential Planners  52.09   2717
                            Planners            56.09   1225
                            Early Bookers       58.37   2669
             Oda + Kahvaltı Last Minuters       37.80     20
                            Potential Planners  31.08     15
                            Planners            29.91      1
                            Early Bookers       28.65      2
             Yarım Pansiyon Last Minuters       30.87     18
                            Potential Planners  23.73      6
                            Planners            27.72      4
                            Early Bookers       40.53      3
Diğer        Herşey Dahil   Last Minuters       75.47    155
                            Potential Planners  85.79    129
                            Planners            87.42     72
                            Early Bookers       92.29    149
             Oda + Kahvaltı Last Minuters       38.11    539
                            Potential Planners  34.98    176
                            Planners            40.71     27
                            Early Bookers       44.25     15
             Yarım Pansiyon Last Minuters       39.47   1173
                            Potential Planners  45.70    605
                            Planners            46.45    139
                            Early Bookers       47.44     61
Girne        Herşey Dahil   Last Minuters       93.25     24
                            Potential Planners  94.95     41
                            Planners           112.18     15
                            Early Bookers       97.72     26
             Oda + Kahvaltı Last Minuters       37.58     62
                            Potential Planners  39.77     39
                            Planners            44.13     24
                            Early Bookers       42.05     14
             Yarım Pansiyon Last Minuters       60.86     73
                            Potential Planners  53.40     81
                            Planners            45.83     32
                            Early Bookers       39.49     24
Muğla        Herşey Dahil   Last Minuters       63.69   3851
                            Potential Planners  62.41   2942
                            Planners            64.72   1353
                            Early Bookers       61.18   1673
             Oda + Kahvaltı Last Minuters       51.09    331
                            Potential Planners  63.11    149
                            Planners            74.53     88
                            Early Bookers       66.73     86
             Yarım Pansiyon Last Minuters       41.88    104
                            Potential Planners  45.29     50
                            Planners            52.58     19
                            Early Bookers       58.46     14
İzmir        Herşey Dahil   Last Minuters       73.25    589
                            Potential Planners  67.77    440
                            Planners            80.88    170
                            Early Bookers       90.38    182
             Oda + Kahvaltı Last Minuters       40.46    163
                            Potential Planners  36.81     41
                            Planners            54.17     15
                            Early Bookers       56.07      9
             Yarım Pansiyon Last Minuters       57.79    636
                            Potential Planners  64.80    198
                            Planners            58.09     40
                            Early Bookers       68.70     21

In [13]:
df.groupby(["SaleCityName", "ConceptName", "Seasons"]).agg({"Price": ["mean","count"]})

                                     Price
                                      mean  count
SaleCityName ConceptName    Seasons
Antalya      Herşey Dahil   High     64.92  27126
                            Low      61.55   3667
             Oda + Kahvaltı High     66.27    303
                            Low      60.67    295
             Yarım Pansiyon High     73.26    118
                            Low      62.00    138
Aydın        Herşey Dahil   High     54.95  10103
                            Low      33.68    473
             Oda + Kahvaltı High     30.39     27
                            Low      44.45     11
             Yarım Pansiyon High     32.63     20
                            Low      25.27     11
Diğer        Herşey Dahil   High     83.79    364
                            Low      87.31    141
             Oda + Kahvaltı High     34.84    349
                            Low      39.96    408
             Yarım Pansiyon High     39.73    516
                            Low      42.95   1462
Girne        Herşey Dahil   High    103.94     55
                            Low      90.94     51
             Oda + Kahvaltı High     39.48     66
                            Low      40.04     73
             Yarım Pansiyon High     58.38    100
                            Low      48.58    110
Muğla        Herşey Dahil   High     63.38   9582
                            Low      48.30    237
             Oda + Kahvaltı High     61.26    592
                            Low      37.77     62
             Yarım Pansiyon High     45.82    177
                            Low      32.68     10
İzmir        Herşey Dahil   High     74.75   1234
                            Low      74.31    147
             Oda + Kahvaltı High     54.14     86
                            Low      33.56    142
             Yarım Pansiyon High     87.66    118
                            Low      55.35    777

In [14]:
df.groupby(["SaleCityName", "ConceptName", "CInDay"]).agg({"Price": ["mean","count"]})

                                       Price
                                        mean count
SaleCityName ConceptName    CInDay
Antalya      Herşey Dahil   Friday     62.66  4136
                            Monday     63.26  6831
                            Saturday   64.42  4741
                            Sunday     65.85  3818
                            Thursday   62.89  3898
                            Tuesday    66.77  3760
                            Wednesday  67.17  3609
             Oda + Kahvaltı Friday     63.13   114
                            Monday     57.17    66
                            Saturday   58.01   117
                            Sunday     63.47    46
                            Thursday   64.65    93
                            Tuesday    65.84    73
                            Wednesday  72.81    89
             Yarım Pansiyon Friday     69.26    38
                            Monday     76.95    20
                            Saturday   63.38    71
                            Sunday     64.45    30
                            Thursday   66.64    40
                            Tuesday    71.02    21
                            Wednesday  67.78    36
Aydın        Herşey Dahil   Friday     51.03  1825
                            Monday     54.38  2566
                            Saturday   56.89  1702
                            Sunday     53.19  1098
                            Thursday   54.51  1315
                            Tuesday    53.51  1098
                            Wednesday  54.22   972
             Oda + Kahvaltı Friday     31.17     7
                            Monday     45.40     7
                            Saturday   23.93     2
                            Sunday     43.53     3
                            Thursday   37.52     7
                            Tuesday    32.93     3
                            Wednesday  25.95     9
             Yarım Pansiyon Friday     24.52     5
                            Monday     43.43     3
                            Saturday   29.70     8
                            Sunday     30.28     3
                            Thursday   22.78     5
                            Tuesday    32.16     4
                            Wednesday  35.55     3
Diğer        Herşey Dahil   Friday     84.66    78
                            Monday     90.60   112
                            Saturday   77.23    90
                            Sunday     81.61    57
                            Thursday   76.11    54
                            Tuesday    90.33    56
                            Wednesday  91.18    58
             Oda + Kahvaltı Friday     38.47   116
                            Monday     36.65    87
                            Saturday   36.40   207
                            Sunday     38.06    67
                            Thursday   35.39    99
                            Tuesday    42.24    80
                            Wednesday  38.05   101
             Yarım Pansiyon Friday     42.37   407
                            Monday     40.28   217
                            Saturday   43.25   638
                            Sunday     41.86   219
                            Thursday   41.95   198
                            Tuesday    43.50   140
                            Wednesday  38.74   159
Girne        Herşey Dahil   Friday    121.19    12
                            Monday     98.66    22
                            Saturday  109.17     9
                            Sunday     85.19    38
                            Thursday  112.38     7
                            Tuesday   111.40     8
                            Wednesday  83.17    10
             Oda + Kahvaltı Friday     45.02    34
                            Monday     40.76    13
                            Saturday   37.18    29
                            Sunday     38.22    20
                            Thursday   36.50    13
                            Tuesday    35.39    19
                            Wednesday  43.52    11
             Yarım Pansiyon Friday     65.54    41
                            Monday     49.55    30
                            Saturday   56.15    26
                            Sunday     48.32    26
                            Thursday   50.92    18
                            Tuesday    50.12    39
                            Wednesday  47.36    30
Muğla        Herşey Dahil   Friday     59.64  1403
                            Monday     63.31  2242
                            Saturday   62.73  1516
                            Sunday     62.75  1234
                            Thursday   63.27  1169
                            Tuesday    66.24  1166
                            Wednesday  63.77  1089
             Oda + Kahvaltı Friday     60.56    87
                            Monday     58.15   114
                            Saturday   55.97   110
                            Sunday     79.19    88
                            Thursday   55.75    75
                            Tuesday    50.89    82
                            Wednesday  53.40    98
             Yarım Pansiyon Friday     38.79    22
                            Monday     47.98    38
                            Saturday   48.63    31
                            Sunday     49.88    20
                            Thursday   37.84    27
                            Tuesday    39.31    28
                            Wednesday  53.97    21
İzmir        Herşey Dahil   Friday     71.40   170
                            Monday     73.25   305
                            Saturday   72.86   283
                            Sunday     75.10   189
                            Thursday   79.07   174
                            Tuesday    75.61   128
                            Wednesday  79.04   132
             Oda + Kahvaltı Friday     46.56    25
                            Monday     43.95    18
                            Saturday   38.64    69
                            Sunday     42.91    26
                            Thursday   39.37    27
                            Tuesday    41.81    28
                            Wednesday  41.44    35
             Yarım Pansiyon Friday     65.38   160
                            Monday     59.80   102
                            Saturday   52.50   315
                            Sunday     98.93    68
                            Thursday   52.48    91
                            Tuesday    56.14    73
                            Wednesday  54.06    86

#### Görev 4: City-Concept-Season kırılımının çıktısını PRICE'a göre sıralayınız.

In [15]:
agg_df = df.groupby(["SaleCityName","ConceptName","Seasons"]).agg({"Price": "mean"}).sort_values("Price", ascending=False)
agg_df.head(20)

                                     Price
SaleCityName ConceptName    Seasons
Girne        Herşey Dahil   High    103.94
                            Low      90.94
İzmir        Yarım Pansiyon High     87.66
Diğer        Herşey Dahil   Low      87.31
                            High     83.79
İzmir        Herşey Dahil   High     74.75
                            Low      74.31
Antalya      Yarım Pansiyon High     73.26
             Oda + Kahvaltı High     66.27
             Herşey Dahil   High     64.92
Muğla        Herşey Dahil   High     63.38
Antalya      Yarım Pansiyon Low      62.00
             Herşey Dahil   Low      61.55
Muğla        Oda + Kahvaltı High     61.26
Antalya      Oda + Kahvaltı Low      60.67
Girne        Yarım Pansiyon High     58.38
İzmir        Yarım Pansiyon Low      55.35
Aydın        Herşey Dahil   High     54.95
İzmir        Oda + Kahvaltı High     54.14
Girne        Yarım Pansiyon Low      48.58

#### Görev 5: Indekste yer alan isimleri değişken ismine çeviriniz.

In [16]:
agg_df.reset_index(inplace= True)
agg_df.head()

  SaleCityName     ConceptName Seasons  Price
0        Girne    Herşey Dahil    High 103.94
1        Girne    Herşey Dahil     Low  90.94
2        İzmir  Yarım Pansiyon    High  87.66
3        Diğer    Herşey Dahil     Low  87.31
4        Diğer    Herşey Dahil    High  83.79

#### Görev 6: Yeni seviye tabanlı müşterileri (persona) tanımlayınız.

In [17]:
agg_df["sales_level_based"] = agg_df[["SaleCityName", "ConceptName", "Seasons"]].agg(lambda x: '_'.join(x).upper(), axis=1)
agg_df.head()

  SaleCityName     ConceptName Seasons  Price          sales_level_based
0        Girne    Herşey Dahil    High 103.94    GIRNE_HERŞEY DAHIL_HIGH
1        Girne    Herşey Dahil     Low  90.94     GIRNE_HERŞEY DAHIL_LOW
2        İzmir  Yarım Pansiyon    High  87.66  İZMIR_YARIM PANSIYON_HIGH
3        Diğer    Herşey Dahil     Low  87.31     DIĞER_HERŞEY DAHIL_LOW
4        Diğer    Herşey Dahil    High  83.79    DIĞER_HERŞEY DAHIL_HIGH

#### Görev 7: Yeni müşterileri (personaları) segmentlere ayırınız.

In [18]:
agg_df["Segments"] = pd.qcut(agg_df["Price"], 4, labels=["D","C","B","A"])
agg_df.groupby("Segments").agg({"Price": ("mean","sum","max")}).sort_values("Segments",ascending=False)

         Price
          mean    sum    max
Segments
A        82.47 742.21 103.94
B        60.27 542.47  64.92
C        44.89 403.99  54.14
D        33.37 300.30  39.48

#### Görev 8: Yeni gelen müşterileri sınıflandırıp, ne kadar gelir getirebileceklerini tahmin ediniz.

In [19]:
agg_df.sort_values("Price")
new_user = "ANTALYA_HERŞEY DAHIL_HIGH"
agg_df[agg_df["sales_level_based"] == new_user]

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,Segments
9,Antalya,Herşey Dahil,High,64.92,ANTALYA_HERŞEY DAHIL_HIGH,B